### ISSUE TITLE
Windows support roadmap

### ISSUE THREAD

**Issue by chvck** [couchbaselabs/couchbase-rs#72]
Right now we cannot compile the SDK in a standard Windows environment. In order to support this we need to:

- [ ]  Get a change made to lcb to not attempt to access TARGET_PDB_FILE when building statically on Windows as it won't exist in that scenario.

- [ ] Get a change upstreamed into the cmake cargo crate to allow us to not set any cmake c flags, doing this upsets the lcb build system.

- [ ] Update build.rs to have Windows specific build options:

- Don't use cmake c flags

- Use the correct couchbase library name and path

- Use Windows libraries with the linker

- [ ] Pull in any changes made to lcb to address the issue with iocp not supporting tick_wait

**Comment by daschl** [comment]
thanks to the great work of @chvck this is done now :)
